version: '2'
services:
  server:
    image: redash/redash:latest
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://127.0.0.1:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@127.0.0.1/postgres"
      REDASH_COOKIE_SECRET: veryverysecret
      REDASH_WEB_WORKERS: 4
    restart: always
  worker:
    image: redash/redash:latest
    command: scheduler
    depends_on:
      - postgres
      - redis
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://127.0.0.1:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@127.0.0.1/postgres"
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 2
    restart: always
  redis:
    image: redis:3.0-alpine
    restart: always
    ports:
      - "6379/tcp"
  postgres:
    image: registry.cn-hangzhou.aliyuncs.com/zqqq/redash-pgsql:9.5.6-alpine
    volumes:
      - /var/lib/postgresql/data
    restart: always
    ports:
      - "5432/tcp"
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/zqqq/redash-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always
