apiVersion: apps/v1
kind: Deployment
metadata:
  name: rainbond-allinone-deployment
  labels:
    app: rainbond-allinone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rainbond-allinone
  template:
    metadata:
      labels:
        app: rainbond-allinone
    spec:
      containers:
      - name: rainbond-allinone
        image: registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond:v5.3.0-release-allinone
        ports:
        - containerPort: 7070
        volumeMounts:
        - mountPath: /root/.ssh
          name: rainbond-ssh
        - mountPath: /app/data
          name: rainbond-data
      volumes:
      - name: rainbond-ssh
        hostPath:
          path: /root/.ssh
      - name: rainbond-data
        hostPath:
          path: /root/rainbonddata
      nodeSelector:
        rainbond: 172.20.1.130
--

apiVersion: v1
kind: Service
metadata:
  name: rainbond-allinone-svc
spec:
  type: NodePort
  selector:
    app: rainbond-allinone
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
      nodePort: 37070