apiVersion: v1
kind: Service
metadata:
  name: rainbond-allinone-svc
spec:
  type: NodePort
  selector:
    app: rainbond-allinone
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
      nodePort: 37070